<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-01-07T17:21:29Z" name="Default suite" finished-at="2019-01-07T17:21:37Z" duration-ms="7999">
    <groups>
    </groups>
    <test started-at="2019-01-07T17:21:29Z" name="Default test" finished-at="2019-01-07T17:21:37Z" duration-ms="7999">
      <class name="com.whitecircleschool.demo.RealProjectLevelA2.loginPageTest">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:com.whitecircleschool.demo.RealProjectLevelA2.loginPageTest@d21a74c]" started-at="2019-01-07T17:21:29Z" name="openBrowser" finished-at="2019-01-07T17:21:35Z" duration-ms="5975" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="loginTest()[pri:0, instance:com.whitecircleschool.demo.RealProjectLevelA2.loginPageTest@d21a74c]" started-at="2019-01-07T17:21:35Z" name="loginTest" finished-at="2019-01-07T17:21:37Z" duration-ms="1992" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [8 W 126th Street, New York,NY 10027, USA] but found [8 W 126th Street, New York,
NY 10027, USA]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [8 W 126th Street, New York,NY 10027, USA] but found [8 W 126th Street, New York,
NY 10027, USA]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.whitecircleschool.demo.RealProjectLevelA2.loginPageTest.loginTest(loginPageTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- com.whitecircleschool.demo.RealProjectLevelA2.loginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
